/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Tech Dark Theme
        "tech-dark-deep": "#020617",
        "tech-dark-surface": "#0F172A",
        "tech-dark-border": "#1E293B",
        // Nova Blue (Primary)
        "nova-blue": "#00e5ff",
        "nova-blue-dim": "rgba(0, 229, 255, 0.15)",
        "primary-container": "#00e5ff",
        "on-primary": "#00363d",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#004f58",
        "on-primary-container": "#00626e",
        "primary-fixed": "#9cf0ff",
        "primary-fixed-dim": "#00daf3",
        "inverse-primary": "#006875",
        // Surface colors
        "surface": "#0d1516",
        "surface-dim": "#0d1516",
        "surface-bright": "#333a3c",
        "surface-container-lowest": "#080f11",
        "surface-container-low": "#151d1e",
        "surface-container": "#192122",
        "surface-container-high": "#242b2d",
        "surface-container-highest": "#2e3638",
        // Text colors
        "on-surface": "#dce4e5",
        "on-surface-variant": "#bac9cc",
        "on-background": "#dce4e5",
        // Secondary
        "secondary": "#b9c7e4",
        "on-secondary": "#233148",
        "secondary-container": "#3c4962",
        "on-secondary-container": "#abb9d6",
        "secondary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#b9c7e4",
        "on-secondary-fixed": "#0d1c32",
        "on-secondary-fixed-variant": "#39475f",
        // Tertiary
        "tertiary": "#ffeac0",
        "on-tertiary": "#3e2e00",
        "tertiary-container": "#fec931",
        "on-tertiary-container": "#6f5500",
        "tertiary-fixed": "#ffdf96",
        "tertiary-fixed-dim": "#f3bf26",
        "on-tertiary-fixed": "#251a00",
        "on-tertiary-fixed-variant": "#594400",
        // Error
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        // Other
        "background": "#0d1516",
        "surface-variant": "#2e3638",
        "surface-tint": "#00daf3",
        "outline": "#849396",
        "outline-variant": "#3b494c",
        "inverse-surface": "#dce4e5",
        "inverse-on-surface": "#2a3233",
        "neon-green": "#10B981",
        "neon-purple": "#8B5CF6",
      },
      fontFamily: {
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code-label": ["JetBrains Mono", "monospace"],
        "status-label": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["60px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-label": ["14px", { lineHeight: "1.5", letterSpacing: "0.02em", fontWeight: "500" }],
        "status-label": ["12px", { lineHeight: "1", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "base": "4px",
        "container-max": "1280px",
        "gutter": "24px",
        "section-gap": "120px",
        "module-padding": "32px",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        glow: "glow 2s ease-in-out infinite",
        scan: "scan 4s linear infinite",
        "random-flicker": "random-flicker var(--flicker-duration, 3s) infinite",
        "flow-in": "flow-in var(--flow-duration, 10s) linear infinite",
        "flow-out": "flow-out var(--flow-duration, 10s) linear infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        glow: {
          "0%, 100%": { opacity: 1 },
          "50%": { opacity: 0.5 },
        },
        scan: {
          "from": { top: "0%" },
          "to": { top: "100%" },
        },
        "random-flicker": {
          "0%, 100%": { opacity: 1, filter: "brightness(1) drop-shadow(0 0 5px currentColor)" },
          "33%": { opacity: 0.8, filter: "brightness(1.2) drop-shadow(0 0 10px currentColor)" },
          "66%": { opacity: 0.9, filter: "brightness(0.9) drop-shadow(0 0 3px currentColor)" },
          "70%": { opacity: 0.5, filter: "brightness(1.5) drop-shadow(0 0 15px currentColor)" },
          "72%": { opacity: 1, filter: "brightness(1) drop-shadow(0 0 5px currentColor)" },
        },
        "flow-in": {
          "0%": { transform: "translate(var(--sx), var(--sy)) scale(1)", opacity: "0.15" },
          "100%": { transform: "translate(-50%, -50%) scale(0.1)", opacity: "0" },
        },
        "flow-out": {
          "0%": { transform: "translate(-50%, -50%) scale(0.1)", opacity: "0" },
          "20%": { opacity: "0.15" },
          "100%": { transform: "translate(var(--tx), var(--ty)) scale(1.5)", opacity: "0" },
        },
      },
      boxShadow: {
        "nova-glow": "0 0 40px rgba(0, 229, 255, 0.15)",
      },
      backgroundImage: {
        "tech-grid": "radial-gradient(circle, #1E293B 1px, transparent 1px)",
      },
    },
  },
  plugins: [],
}
